### ISSUE TITLE
Import crashes due to unknow cause

### ISSUE THREAD

**Issue by reinvantveer** [histograph/import#3]
```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request.optionalCallback [as _callback] (/opt/histograph/import/index.js:38:42)
    at Request.self.callback (/opt/histograph/import/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/opt/histograph/import/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/opt/histograph/import/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

**Comment by rutgervanwilligen** [comment]
fixed by changing port number in latest histograph/config commit
